language: java
jdk:
 - oraclejdk8
sudo: false

cache:
  directories:
  - $HOME/.m2
    
#script: "mvn clean verify"
after_success:
  - mvn clean test org.jacoco:jacoco-maven-plugin:report org.eluder.coveralls:coveralls-maven-plugin:report