language: java
jdk:
 - oraclejdk8
sudo: false

cache:
  directories:
  - $HOME/.m2
    
#script: "mvn clean verify"
script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - mvn -f clean verify -Pjacoco coveralls:report