language: java
jdk:
 - oraclejdk8
sudo: false

addons:
  sonarcloud:
    organization: "softmill"
    token:
      secure: "9fa5d2f620e38b07e8f421638fd751c9da052d22"
      
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
install: true
    
#script: "mvn clean verify"
after_success:
  - mvn clean verify -Pjacoco org.eluder.coveralls:coveralls-maven-plugin:report 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar