language: java
jdk:
 - oraclejdk8
sudo: false

addons:
  sonarcloud:
    organization: "crejczyk-github"
    token:
      secure: "44049eba83d0b9b33ca261c675fb55175c2e0d90"
      
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
install: true

after_success:
  - mvn clean verify -Pjacoco org.eluder.coveralls:coveralls-maven-plugin:report sonar:sonar