language: java
jdk:
 - oraclejdk8
sudo: false

cache:
  directories:
  - $HOME/.m2

env:
  global:
    - CODECOV_TOKEN=fa349510-8e2d-4f12-91df-2cba5b06629d

addons:
  sonarcloud:
    organization: "crejczyk-github"
    token:
      secure: "fa349510-8e2d-4f12-91df-2cba5b06629d"

    
#script: "mvn clean verify"
script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - mvn clean verify -Pjacoco coveralls:report

after_success:
  - bash <(curl -s https://codecov.io/bash)